services:
  mysql:
    container_name: mysql
    image: arm64v8/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: jdbctest
      MYSQL_DATABASE: jdbc_security
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/data/mysql

  elasticsearch:
    container_name: elasticsearch
    image: arm64v8/elasticsearch:8.8.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/data/elasticsearch
