spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/project
    username: root
    password: jdbctest

  data:
    elasticsearch:
      cluster-node: localhost:9200


server:
  error:
    include-binding-errors: always
    include-message: always